services:
    - docker

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull "$DOCKER_USERNAME"/cosmoinformatics

script:
    - docker run --rm "$DOCKER_USERNAME"/cosmoinformatics /bin/sh -c "git checkout ${TRAVIS_BRANCH}"
