git:
    lfs_skip_smudge: true
language: python
python: "3.8"
before_install:
    - sudo apt-get update
    - sudo apt-get -y install libmpc-dev libmpfr-dev
install: pip install -r requirements.txt
before_script:
    - >
        git lfs pull --include EGM2008_Topography_flms_L2190.mat
script: pytest -v --runslow
