services:
    - docker

addons:
    apt:
        packages:
            - docker-ce

before_script:
    - docker --version
    - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin

script:
    - docker build -f docker/Dockerfile .
