language: python
python:
    - '3.6'

services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull paddyroddy/cosmoinformatics
    - docker run -it --rm paddyroddy/cosmoinformatics
    - git checkout "$TRAVIS_BRANCH"

script:
    - python pys2sleplet_tests.py
