language: python
python:
    - '3.6'

services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull "$DOCKER_USERNAME"/cosmoinformatics
    - git checkout "$TRAVIS_BRANCH"

script:
    - docker run --rm "$DOCKER_USERNAME"/cosmoinformatics /bin/sh -c "python pys2sleplet_tests.py"
