services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
    - docker pull "$DOCKER_USERNAME"/cosmoinformatics
    - docker run --name run_test -t -d "$DOCKER_USERNAME"/cosmoinformatics

before_script:
    - docker exec run_test mkdir s2sleplet
    - docker cp . run_test:s2sleplet
    - docker exec run_test sed -i "s/32/512/" input.yml

script:
    - docker exec run_test ./pys2sleplet_tests.py
