git:
    lfs_skip_smudge: true
language: python
python: "3.8"
before_install:
    - sudo apt-get update
    - sudo apt-get -y install libmpc-dev libmpfr-dev
install:
    - pip install -r requirements_travis.txt
before_script:
    - >
        git lfs pull -I
        EGM2008_Topography_flms_L2190.mat,polar40_L32.npy,
        polar40_outline.npy,
        theta30-60_phi30-60_L32.npy,
        theta30-60_phi30-60_outline.npy
script:
    - pytest -v --runslow
