services:
    - docker

before_install:
    - >
        echo ${DOCKER_PASSWORD} |
        docker login
        -u ${DOCKER_USERNAME}
        --password-stdin

install:
    - >
        docker build
        -f docker/Dockerfile
        --build-arg DOCKER_USERNAME=${DOCKER_USERNAME}
        --build-arg DOCKER_IMAGE=${DOCKER_IMAGE}
        -t image
        .

before_script:
    - >
        docker run
        --name container
        -t
        -d image

script:
    - >
        docker exec
        container
        pytest --runslow -v
