[type.py]
extend-ignore-re = [
    "(?:=|>|<)\\s*color",
    "\"(?:color\":\\s\"|ax\":\\s)",
    "\\.Center\\(",
    "\\w=\"center\"",
    "ax(?:s?[,.]\\w|\\s*=\\s*\\w|,|\\[|:\\s\\w)",
    "center=\\w",
    "color(?:=\"|=\\w|\\.colors\\.|_range)",
    "mpl\\.colors\\.",
]
