name: py39

channels:
    - conda-forge

dependencies:
    - igl=2.2.1
    - mpc=1.1.0
    - mpfr=4.1.0
    - pip=21.2.4
    - plotly-orca=1.3.1
    - python=3.9.6

    - pip:
          - -r requirements.txt
