name: s2sleplet

channels:
    - conda-forge

dependencies:
    - igl=2.2.1
    - mpc=1.2.1
    - mpfr=4.1.0
    - pip=22.0.4
    - plotly-orca=1.3.1
    - python=3.10

    - pip:
          - -r requirements.txt
