[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
authors = [{email = "patrickjamesroddy@gmail.com", name = "Patrick Roddy"}]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
  "cmocean==2.0",
  "gmpy2==2.1.2",
  "hypothesis==6.56.4",
  "kaleido==0.2.1",
  "matplotlib==3.6.0",
  "multiprocess==0.70.14",
  "numba==0.56.3",
  "numpy==1.23.4",
  "pandas==1.5.1",
  "plotly==5.11.0",
  "pre-commit==2.20.0",
  "psutil==5.9.3",
  "pys2let==2.2.4",
  "pyssht==1.5.1",
  "pytest==7.2.0",
  "python-box[toml]==6.1.0",
  "requests==2.28.1",
  "scipy==1.9.3",
  "seaborn==0.12.1",
]
description = "Slepian Scale-Discretised Wavelets"
keywords = ["manifolds", "python", "slepian-functions", "sphere", "wavelets"]
license = {text = "BSD-3-Clause"}
name = "sleplet"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.3"

[project.scripts]
mesh = "sleplet.scripts.plotting_on_mesh:main"
sphere = "sleplet.scripts.plotting_on_sphere:main"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.ruff]
force-exclude = true
ignore = ["E741", "W605"]
select = [
  # flake8-bugbear
  "B",
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # pylint
  "PLE",
  "PLR",
  "PLW",
  # flake8-quotes
  "Q",
  "W",
  # flake8-2020
  "YTT",
]

[tool.ruff.mccabe]
max-complexity = 18

[tool.tomlsort]
all = true
trailing_comma_inline_array = true
