[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
authors = [{email = "patrickjamesroddy@gmail.com", name = "Patrick Roddy"}]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
  "cmocean @ https://github.com/matplotlib/cmocean/archive/refs/heads/main.zip",
  "gmpy2==2.1.5",
  "hypothesis==6.67.1",
  "kaleido==0.2.1",
  "libigl==2.4.1",
  "matplotlib==3.6.3",
  "multiprocess==0.70.14",
  "numba==0.56.4",
  "numpy==1.23.5",
  "pandas==1.5.3",
  "plotly==5.13.0",
  "psutil==5.9.4",
  "pydantic==1.10.4",
  "pys2let==2.2.4",
  "pyssht==1.5.1",
  "python-box[toml]==7.0.0",
  "scipy==1.10.0",
  "seaborn==0.12.2",
]
description = "Slepian Scale-Discretised Wavelets"
keywords = ["manifolds", "python", "slepian-functions", "sphere", "wavelets"]
license = {text = "BSD-3-Clause"}
name = "sleplet"
readme = "README.md"
requires-python = "~=3.10"
version = "0.1.5"

[project.optional-dependencies]
dev = [
  "black",
  "mypy",
  "pre-commit",
  "tox",
]

[project.scripts]
mesh = "sleplet.scripts.plotting_on_mesh:main"
sphere = "sleplet.scripts.plotting_on_sphere:main"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin", "pydantic.mypy"]

[tool.pytest.ini_options]
addopts = "--color=yes -v"

[tool.ruff]
fix = true
force-exclude = true
ignore = ["E741", "PLR0913", "W605"]
select = [
  # flake8-bugbear
  "B",
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # isort
  "I",
  # pylint
  "PLE",
  "PLR",
  "PLW",
  # flake8-quotes
  "Q",
  "W",
  # flake8-2020
  "YTT",
]

[tool.ruff.mccabe]
max-complexity = 18

[tool.tomlsort]
all = true
trailing_comma_inline_array = true

[tool.tox]
legacy_tox_ini = """
    [gh-actions]
    python =
        3.10: py310

    [testenv]
    commands =
        pytest \
        --cov=sleplet \
        --runslow
    deps =
        pytest
        pytest-cov

    [tox]
    env_list =
        py310
"""
