AUTO_OPEN = true
INTENSITY_FACES = true
L = 16
L_MIN = 0
L_MAX = -1
LAPLACIAN = "mesh"
NCPU = 4
NORMALISE = true
PHI_MIN = 0
PHI_MAX = 360
POLAR_GAP = false
SAMPLES = 2
SAVE_FIG = false
SAVE_MATRICES = false
SLEPIAN_MASK = "south_america"
THETA_MIN = 0
THETA_MAX = 180
UPSAMPLE = true
