[default]
ncpu = 4
auto_open = true
polar_gap = false
save_fig = false
save_matrices = false
L = 16
theta_min = 0
theta_max = 180
phi_min = 0
phi_max = 360
order = 0
slepian_mask = ""

[travis]
# above 512 get a memory error from travis
L = 512
