auto_open = true
L = 64
L_min = 0
L_max = -1
ncpu = 4
normalise = true
phi_min = 0
phi_max = 360
polar_gap = false
save_fig = false
save_matrices = false
slepian_mask = "south_america"
theta_min = 0
theta_max = 180
upsample = true
