auto_open = true
L = 32
L_min = 0
L_max = -1
ncpu = 4
normalise = true
phi_min = 0
phi_max = 360
polar_gap = false
save_fig = true
save_matrices = false
slepian_mask = ""
theta_min = 0
theta_max = 40
upsample = true
