AUTO_OPEN = true
L = 16
L_MAX = -1
L_MIN = 0
NCPU = 4
PHI_MAX = 360
PHI_MIN = 0
POLAR_GAP = false
SAMPLES = 2
SAVE_FIG = false
SAVE_MATRICES = false
SLEPIAN_MASK = "africa"
THETA_MAX = 180
THETA_MIN = 0
