name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Install other dependencies
              run: sudo apt-get install libmpc-dev libmpfr-dev

            - uses: actions/checkout@v2
            - name: Cache conda
              uses: actions/cache@v1
              with:
                  path: ~/conda_pkgs_dir
                  key: ${{ hashFiles('environment.yml') }}

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: py39
                  environment-file: environment.yml
                  use-only-tar-bz2: true

            - name: Pull LFS files
              run: |
                  git lfs ls-files -I \
                  EGM2008_Topography_flms_L2190.mat,\
                  polar40_L32.npy,\
                  polar40_outline.npy,\
                  theta30-60_phi30-60_L32.npy,\
                  theta30-60_phi30-60_outline.npy \
                  -l | cut -d' ' -f1 | sort > .lfs-assets-id
                  git lfs pull

            - name: Test with pytest
              shell: bash -l {0}
              run: pytest -v --runslow
