name: deploy

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Restore conda cache
              uses: actions/cache@v2
              env:
                  # Increase this value to reset cache if
                  # environment.yml has not changed
                  CACHE_NUMBER: 0
              with:
                  path: ~/conda_pkgs_dir
                  key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
                      hashFiles('environment.yml') }}

            - name: Restore pip cache
              uses: actions/cache@v2
              with:
                  # This path is specific to Ubuntu
                  path: ~/.cache/pip
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
                      ${{ runner.os }}-

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: py39
                  channel-priority: strict
                  environment-file: environment.yml
                  use-only-tar-bz2: true

            - name: Conan remotes
              run: |
                  conan remote list

            - name: Pull LFS files
              run: |
                  git lfs ls-files -I \
                  EGM2008_Topography_flms_L2190.mat,\
                  mesh/basis_functions/bird_b697,\
                  polar40_L32.npy,\
                  theta30-60_phi30-60_L32.npy\
                  -l | cut -d' ' -f1 | sort > .lfs-assets-id
                  git lfs pull

            - name: Test with pytest
              run: pytest -v --runslow
