name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@cb2aa7136f05f811c95116b2fb404a7f299102d9 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.11"
