---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@fa62b1a34c1455612031d36abf65f9e792966c95 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.11"
