name: Runs tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding pyproject file
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Pip install modules
        run: pip install -e .

      - name: Pull LFS files
        run: |
          git lfs ls-files -I \
          EGM2008_Topography_flms_L2190.mat,\
          mesh/basis_functions/bird_b697,\
          polar40_L32.npy,\
          theta30-60_phi30-60_L32.npy\
          -l | cut -d' ' -f1 | sort > .lfs-assets-id
          git lfs pull

      - name: Test with pytest
        run: pytest --color=yes --runslow -v
