---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@1a3be93a5bbb79658efc285ce792da79745d9d32 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.11"
