name: Runs tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: cache stuff
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}
          key: |
            sleplet-${{ env.PY }}

      - name: Pip install modules
        run: pip install .[dev]

      - name: Pull LFS files
        run: |
          git lfs ls-files -I \
          EGM2008_Topography_flms_L2190.mat,\
          mesh/basis_functions/bird_b697,\
          polar40_L32.npy,\
          theta30-60_phi30-60_L32.npy\
          -l | cut -d' ' -f1 | sort > .lfs-assets-id
          git lfs pull

      - name: Test with pytest
        run: pytest -v --runslow --color=yes --cov=sleplet
