name: Docs

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: nschloe/action-cached-lfs-checkout@v1
        with:
          include: |
            D_south_america_L128_N690,\
            EGM2008_Topography_flms_L2190.mat

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install rundoc

      - name: Execute README
        run: rundoc run README.md
