---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@18d8678a5aea33da18556ae7823433325631dadd # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/sleplet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          template-directory: ./documentation
