---
name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@f8793becd1b97caa5b40ebc7556b21d9a272d700 # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/sleplet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          template-directory: ./documentation
