---
name: Documentation

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@fa62b1a34c1455612031d36abf65f9e792966c95 # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/sleplet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          python-version: "3.11"
          template-directory: ./documentation
