name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/pdoc@19b19e930f3c18ea1a0317b831047b1c038e098a # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/sleplet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          python-version: "3.11"
          template-directory: ./documentation
