---
name: Examples

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
    paths:
      - "**/*"
      - "!**/*.cff"
      - "!**/*.in"
      - "!**/*.md"
      - "!**/*.txt"
      - "!**/.*"
      - "!.github/ISSUE_TEMPLATES/**"
      - "!documentation/**"
      - "!paper/**"
      - "!tests/**"
  pull_request:
    paths:
      - "**/*"
      - "!**/*.cff"
      - "!**/*.in"
      - "!**/*.md"
      - "!**/*.txt"
      - "!**/.*"
      - "!.github/ISSUE_TEMPLATES/**"
      - "!documentation/**"
      - "!paper/**"
      - "!tests/**"

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  codeblocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ~/.cache/sleplet
          key: readme-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[readme]

      - name: Run examples in the README
        run: python -m pytest --codeblocks .github README.md documentation

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ~/.cache/sleplet
          key: examples-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[docs]

      - name: Run examples in the examples folder
        run: >-
          find examples -name "*.py"
          -exec sh -c 'for f;
          do printf "\n$f\n";
          python "$f" || exit 1;
          done' sh {} +
