---
name: Examples

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  codeblocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.cache/sleplet
          key: readme-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e ".[readme]"

      - name: Run examples in the README
        run: >-
          python -m pytest --codeblocks .github README.md documentation -n auto

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Cache pooch
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.cache/sleplet
          key: examples-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[docs]

      - name: Run examples in the examples folder
        run: >-
          find examples -name "*.py" -exec sh -c 'for f; do printf "\n$f\n";
          python "$f" || exit 1; done' sh {} +
