name: Examples

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Run rundoc on the README
        run: rundoc run README.md

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Execute all examples in folders
        run: |
          find examples -name '*.py'
          -exec echo {} \;
          -exec echo  \;
          -exec python {} \;
