---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@cde57fbdb1dcdc4cd2aacb0d34127e1582424621 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./LICENCE.txt
