---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@cde57fbdb1dcdc4cd2aacb0d34127e1582424621 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
