name: Linting

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: tox-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: pre-commit run --all-files --color always

      - name: run sourcery
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}

      - name: check-manifest
        uses: tj-actions/check-manifest@v1
