---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@f8793becd1b97caa5b40ebc7556b21d9a272d700 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
