name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@vx.y.z
        with:
          pre-commit-config: ./.pre-commit-config.yaml
