name: Run Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: restore python cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

            - name: Install dependencies
              run: |
                  sudo apt-get -y install libmpc-dev libmpfr-dev
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: pull LFS files
              run: |
                  git lfs pull -I \
                  EGM2008_Topography_flms_L2190.mat,\
                  polar40_L32.npy,\
                  polar40_outline.npy,\
                  theta30-60_phi30-60_L32.npy,\
                  theta30-60_phi30-60_outline.npy

            - name: Test with pytest
              run: |
                  pytest -v --runslow
