name: Test

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: paddyroddy/.github/actions/python/tox@a5fa225f79b16f86bd36bbaf64d0efa9b5f6a78a # v0
        with:
          cache-path: |-
            .tox
            ~/.cache/sleplet
          operating-system: ${{ matrix.os }}
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2
        with:
          flag-name: run-${{ matrix.os }}-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2
        with:
          parallel-finished: true
          carryforward: "\
            run-macos-latest-3.10,\
            run-ubuntu-latest-3.10,\
            run-macos-latest-3.11,\
            run-ubuntu-latest-3.11\
            "
