name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "paper/**"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache tox/pooch
        uses: actions/cache@v3
        with:
          path: |
            .tox
            ~/.cache/sleplet
          key: test-${{ hashFiles('pyproject.toml') }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/astro-informatics/s2wav.git
          git clone https://github.com/astro-informatics/s2fft.git
          pip install -e ./s2wav
          pip install -e ./s2fft
          pip install jaxlib

      - name: Check s2wav installation worked
        run: |
          import s2wav
        shell: python

      - name: Check s2fft installation worked
        run: |
          import s2fft
        shell: python
